package com.epam.webproject.controller.command;

public enum CommandType {
    SIGN_IN_COMMAND,
    SIGN_UP_COMMAND,
    DEFAULT,
    GO_TO_LOGIN_PAGE_COMMAND,
    GO_TO_HOME_PAGE_COMMAND,
    GO_TO_REGISTRATION_PAGE_COMMAND,
    CHANGE_LOCALE_COMMAND,
    GO_TO_ADD_TASK_PAGE_COMMAND,
    ADD_TASK_COMMAND,
    SIGN_OUT_COMMAND,
    ADD_ANSWER_COMMAND,
    ADD_COMMENT_COMMAND;

}